### PR TITLE
Fix memory leak in encoder/decoders related to ByteBuf

### PR DESCRIPTION
**Pull request by wpnpeiris**
Problem:
See  #21 for the description of the problem

Solution:
- Use Pooled ByteBufAllocator in creating ByteBuf
- Release ByteBuf reference in okapies.finagle.kafka.protocol.Message
- Release ByteBuf references in okapies.finagle.kafka.protocol.Spec after usage

### CODE REVIEW

**Comment by okapies** [comment]
@mkhq I think it is LGTM but does it also work in your environment?

(Honestly, as you noticed, I don't use Scala and Finagle at the moment because my company mainly uses Python and focuses on the deep-learning technology in B2B area. I'd like to grant you permission
 or transfer this repository to you if you're interested in becoming a maintainer. How do you think?)

**Comment by mkhq** [comment]
@okapies It works great for our environment, @wpnpeiris is working with me Hive Streaming.

I would be happy to take over maintaining this library, thank you for the opportunity :)

**Comment by okapies** [comment]
Thanks so much! I added @mkhq and @wpnpeiris as a collaborator of the project. Feel free to push the "merge" button for your works.

**Comment by okapies** [comment]
And, of course, you can maintain the Maven package under your (personal or company?) account.

**Review by mkhq — APPROVED** [review]
Looks fine 👍 It has also been tested in production.

**Pull request merged**
