### PR TITLE
Kafka server implementation

### PR DESCRIPTION
**Pull request by mkhq**
This PR implements the kafka server request/response protocol. It makes it possible to create, for example, a finagle-based kafka broker or proxy.

- Implements request decoding and response encoding
- Creates server wiring with a netty pipeline and a finagle DefaultServer
- High-level tests for each request and response
- Only implements v0 of CommitOffsetRequests

### CODE REVIEW

**Comment by okapies** [comment]
Awesome! Please give me some days to review them :)

**Comment by mkhq** [comment]
Sure! Thanks for looking into the code :)

**Comment by okapies** [comment]
I'm sorry to be so long for reviewing. It seems to have no problem to be merged.

Thanks for your great contribution! A new JAR will be published soon.

**Comment by mkhq** [comment]
Great! Thanks :)

**Pull request merged**
